import pandas as pd


RESIDENTIAL = {
    'SINGLE FAMILY DWELLING', 'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)',
    'CONDOMINIUM/TOWNHOUSE', 'OTHER RESIDENCE', 'PORCH, RESIDENTIAL',
    'DRIVEWAY', 'GARAGE/CARPORT', 'YARD (RESIDENTIAL/BUSINESS)',
    'HOTEL', 'MOTEL', 'GROUP HOME', 'MISSIONS/SHELTERS',
    'TRANSITIONAL HOUSING/HALFWAY HOUSE', 'FRAT HOUSE/SORORITY/DORMITORY',
    'FOSTER HOME BOYS OR GIRLS*', 'PROJECT/TENEMENT/PUBLIC HOUSING',
    "MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV'S/MOTORHOME",
    "SINGLE RESIDENCE OCCUPANCY (SRO'S) LOCATIONS", 'SHORT-TERM VACATION RENTAL',
    'STORAGE SHED', 'TOOL SHED*', 'BALCONY*', 'PATIO*', 'STAIRWELL*',
    'APARTMENT/CONDO COMMON LAUNDRY ROOM'
}

COMMERCIAL = {
    'OTHER BUSINESS', 'RESTAURANT/FAST FOOD', 'BAR/SPORTS BAR (OPEN DAY & NIGHT)',
    'BAR/COCKTAIL/NIGHTCLUB', 'NIGHT CLUB (OPEN EVENINGS ONLY)', 'GAS STATION',
    'SHOPPING MALL (COMMON AREA)', 'DEPARTMENT STORE', 'CLOTHING STORE',
    'LIQUOR STORE', 'DRUG STORE', 'MINI-MART', 'MARKET', 'OTHER STORE',
    'BEAUTY SUPPLY STORE', 'CELL PHONE STORE', 'ELECTRONICS STORE (IE:RADIO SHACK, ETC.)',
    'JEWELRY STORE', 'FURNITURE STORE', 'HARDWARE/BUILDING SUPPLY',
    'AUTO REPAIR SHOP', 'AUTO DEALERSHIP (CHEVY, FORD, BMW, MERCEDES, ETC.)',
    'AUTO SALES LOT', 'AUTO SUPPLY STORE*', 'CAR WASH', 'TOW YARD*',
    'BANK', 'SAVINGS & LOAN', 'CREDIT UNION', 'FINANCE COMPANY',
    'AUTOMATED TELLER MACHINE (ATM)', 'CHECK CASHING*', 'PAWN SHOP',
    'OFFICE BUILDING/OFFICE', 'WAREHOUSE', 'FACTORY', 'CONSTRUCTION SITE',
    'PUBLIC STORAGE', 'PARKING LOT', 'PARKING UNDERGROUND/BUILDING',
    'HEALTH SPA/GYM', 'MASSAGE PARLOR', 'NAIL SALON', 'BEAUTY/BARBER SHOP',
    'LAUNDROMAT', 'CLEANER/LAUNDROMAT',
    "COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET'S, ETC.)",
    "DIY CENTER (LOWE'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)",
    'DISCOUNT STORE (99 CENT,DOLLAR,ETC.', 'MEMBERSHIP STORE (COSTCO,SAMS CLUB)*',
    'GUN/SPORTING GOODS', 'SWAP MEET', 'TOBACCO SHOP', 'BOOK STORE',
    'RECORD-CD MUSIC/COMPUTER GAME STORE', 'VIDEO RENTAL STORE', 'TATTOO PARLOR*',
    'PHARMACY INSIDE STORE OR SUPERMARKET*',
    "SEX ORIENTED/BOOK STORE/STRIP CLUB/GENTLEMAN'S CLUB",
    'MEDICAL MARIJUANA FACILITIES/BUSINESSES', 'CATERING/ICE CREAM TRUCK',
    'DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*', 'DRIVE THRU*',
    'DRIVE THRU BANKING (WINDOW)*', 'MAIL BOX', 'POST OFFICE',
    'COMPUTER SERVICES/REPAIRS/SALES', 'TV/RADIO/APPLIANCE', 'SURPLUS SURVIVAL STORE',
    'EQUIPMENT RENTAL', 'RECYCLING CENTER', 'GARMENT MANUFACTURER',
    'MANUFACTURING COMPANY', 'OIL REFINERY', 'ENERGY PLANT/FACILITY',
    'CHEMICAL STORAGE/MANUFACTURING PLANT', 'WATER FACILITY',
    'BANKING INSIDE MARKET-STORE *', 'BANK DROP BOX/MONEY DROP-OUTSIDE OF BANK*',
    'VALET', 'PUBLIC RESTROOM(INDOORS-INSIDE)', 'ELEVATOR', 'ESCALATOR*'
}

OUTDOOR = {
    'SIDEWALK', 'STREET', 'ALLEY', 'PARK/PLAYGROUND', 'BEACH',
    'VACANT LOT', 'TRASH CAN/TRASH DUMPSTER', 'TRAIN TRACKS', 'FREEWAY',
    'BUS STOP', 'BUS STOP/LAYOVER (ALSO QUERY 124)', 'UNDERPASS/BRIDGE*',
    'PEDESTRIAN OVERCROSSING', 'RIVER BED*', 'DAM/RESERVOIR', 'MUSCLE BEACH',
    'BASKETBALL COURTS', 'HANDBALL COURTS', 'SKATEBOARD FACILITY/SKATEBOARD PARK*',
    'GOLF COURSE*', 'POOL-PUBLIC/OUTDOOR OR INDOOR*', 'PUBLIC RESTROOM/OUTSIDE*',
    'OTHER/OUTSIDE', 'TRANSIENT ENCAMPMENT', 'ABANDONED BUILDING ABANDONED HOUSE',
    'TUNNEL', 'CEMETARY*', 'SLIPS/DOCK/MARINA/BOAT', 'ABATEMENT LOCATION',
    'SEWAGE FACILITY/PIPE', 'MASS GATHERING LOCATION', 'FIXED OBJECT'
}

TRANSIT = {
    'VEHICLE, PASSENGER/TRUCK', 'TRUCK, COMMERICAL', 'TAXI', 'AIRCRAFT',
    'MTA BUS', 'GREYHOUND OR INTERSTATE BUS', 'BUS-CHARTER/PRIVATE',
    'OTHER INTERSTATE, CHARTER BUS', 'BUS, SCHOOL, CHURCH',
    'MUNICIPAL BUS LINE INCLUDES LADOT/DASH', 'METROLINK TRAIN', 'AMTRAK TRAIN',
    'OTHER RR TRAIN (UNION PAC, SANTE FE ETC', 'TRAM/STREETCAR(BOXLIKE WAG ON RAILS)*',
    'TRAIN DEPOT/TERMINAL, OTHER THAN MTA', 'TERMINAL, OTHER THAN MTA',
    'BUS DEPOT/TERMINAL, OTHER THAN MTA', 'LA UNION STATION (NOT LINE SPECIFIC)',
    '7TH AND METRO CENTER (NOT LINE SPECIFIC)', 'HARBOR FRWY STATION (NOT LINE SPECIFIC)',
    'TRANSPORTATION FACILITY (AIRPORT)', 'MTA PROPERTY OR PARKING LOT',
    'TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)'
}

EDUCATION = {
    'ELEMENTARY SCHOOL', 'JUNIOR HIGH SCHOOL', 'HIGH SCHOOL',
    'COLLEGE/JUNIOR COLLEGE/UNIVERSITY', 'PRIVATE SCHOOL/PRESCHOOL',
    'SPECIALTY SCHOOL/OTHER', 'TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*',
    'LIBRARY', 'DAY CARE/CHILDREN*', 'DAY CARE/ADULTS*'
}

HEALTHCARE = {
    'HOSPITAL', 'NURSING/CONVALESCENT/RETIREMENT HOME', 'HOSPICE',
    'MEDICAL/DENTAL OFFICES', 'VETERINARIAN/ANIMAL HOSPITAL',
    'VISION CARE FACILITY*', 'OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*',
    'METHADONE CLINIC', 'ABORTION CLINIC/ABORTION FACILITY*'
}

GOVERNMENT = {
    'GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)', 'POLICE FACILITY',
    'FIRE STATION', 'DETENTION/JAIL FACILITY', 'DEPT OF DEFENSE FACILITY',
    'TELECOMMUNICATION FACILITY/LOCATION'
}

ENTERTAINMENT = {
    'THEATRE/MOVIE', 'ENTERTAINMENT/COMEDY CLUB (OTHER)', 'SPORTS ARENA',
    'COLISEUM', 'DODGER STADIUM', 'STAPLES CENTER *', 'SPORTS VENUE, OTHER',
    'AMUSEMENT PARK*', 'ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*',
    'BOWLING ALLEY*', 'SKATING RINK*', 'HOCKEY RINK/ICE HOCKEY',
    'HORSE RACING/SANTA ANITA PARK*', 'CONVENTION CENTER', 'MUSEUM',
    'CULTURAL SIGNIFICANCE/MONUMENT', 'STUDIO (FILM/PHOTOGRAPHIC/MUSIC)',
    'THE GROVE', 'THE BEVERLY CONNECTION', 'THE BEVERLY CENTER',
    'CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)', 'SYNAGOGUE/TEMPLE',
    'MOSQUE*', 'OTHER PLACE OF WORSHIP'
}

DIGITAL = {'CYBERSPACE', 'WEBSITE'}

UNKNOWN = {'Unknown', 'RETIRED (DUPLICATE) DO NOT USE THIS CODE'}

# Build lookup dict once at module level — O(1) per lookup
_PREMISE_MAP = (
    {v: 'Residential'   for v in RESIDENTIAL}   |
    {v: 'Commercial'    for v in COMMERCIAL}     |
    {v: 'Outdoor'       for v in OUTDOOR}        |
    {v: 'Transit'       for v in TRANSIT}        |
    {v: 'Education'     for v in EDUCATION}      |
    {v: 'Healthcare'    for v in HEALTHCARE}     |
    {v: 'Government'    for v in GOVERNMENT}     |
    {v: 'Entertainment' for v in ENTERTAINMENT}  |
    {v: 'Digital'       for v in DIGITAL}        |
    {v: 'Unknown'       for v in UNKNOWN}
)


def add_premise_features(df: pd.DataFrame) -> pd.DataFrame:
    print("  [premise] Grouping premise descriptions...")

    # MTA entries handled via startswith — too many to list manually
    mta_mask = df['premise_description'].str.startswith('MTA', na=False)
    df['premise_group'] = df['premise_description'].map(_PREMISE_MAP).fillna('Other')
    df.loc[mta_mask, 'premise_group'] = 'Transit'

    other_pct = (df['premise_group'] == 'Other').mean()
    print(f"  [premise] Distribution:\n{df['premise_group'].value_counts()}")
    print(f"  [premise] 'Other' coverage: {other_pct:.1%}")

    return df